### ISSUE TITLE
sample code snippets

### ISSUE THREAD

**Issue by asm582** [IBMSpectrumComputing/lsf-git-ops#1]
Hello, can we request for sample code snippets, please?

**Comment by xunpan** [comment]
@asm582 Could you please help to explain more about what did you mean for sample code snippets?

Currently, if you'd like to try `lsf-git-ops`, you can follow steps in README
https://github.com/IBMSpectrumComputing/lsf-git-ops#single-cluster-deployment

**Comment by asm582** [comment]
@xunpan Thanks, closing the issue.
